### ISSUE TITLE
Links in ArchieML sometimes handled incorrectly

### ISSUE THREAD

**Issue by abstrctn** [newsdev/driveshaft#28]
In the following google doc, if the last **TKTKTK »** is a link, the link is malformed in the output

```yaml
[items]

use: y
kicker: TK
text: TK  |  TKTK  |  TKTKTK »
```

```json
items: [
  {
    "use": "y",
    "kicker": "TK",
    "text": "TK  |  TKTK  |  <a href="http://www.nytimes.com">"
}
```
